spring:
  datasource:
    platform: mysql
    url: jdbc:mysql://localhost:3306/crm_catalog?useUnicode=true&useLegacyDatetimeCode=false&serverTimezone=Turkey
    username: root
    password: 14Ocak2020
    hikari:
      connection-timeout: 3000
      idle-timeout: 60000
      max-lifetime: 180000
      maximum-pool-size: 3
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

---

spring:
  profiles: prod
  datasource:
    platform: mysql
    url: jdbc:mysql://crm-mysql-catalog-service:${MYSQL_PORT}/${MYSQL_DATABASE}?createDatabaseIfNotExist=true&useSSL=false&AllowPublicKeyRetrieval=True
    username: root
    password: ${MYSQL_ROOT_PASSWORD}
    hikari:
      connection-timeout: 3000
      idle-timeout: 60000
      max-lifetime: 180000
      maximum-pool-size: 3
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
