//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.20 at 02:49:02 PM EET 
//


package com.turkcell.crm.catalog.soap;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.turkcell.crm.catalog.soap package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.turkcell.crm.catalog.soap
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetAllCatalogResponse }
     * 
     */
    public GetAllCatalogResponse createGetAllCatalogResponse() {
        return new GetAllCatalogResponse();
    }

    /**
     * Create an instance of {@link CatalogResponse }
     * 
     */
    public CatalogResponse createCatalogResponse() {
        return new CatalogResponse();
    }

    /**
     * Create an instance of {@link ResponseMessage }
     * 
     */
    public ResponseMessage createResponseMessage() {
        return new ResponseMessage();
    }

    /**
     * Create an instance of {@link GetAllCatalogRequest }
     * 
     */
    public GetAllCatalogRequest createGetAllCatalogRequest() {
        return new GetAllCatalogRequest();
    }

}
